/*
 *   This file will be regenerated by `mulle-sourcetree-to-c --project-dialect objc` via
 *   `mulle-sde reflect` and any edits will be lost.
 *   Suppress generation of this file with:
 *
 *      mulle-sde environment set MULLE_SOURCETREE_TO_C_IMPORT_FILE DISABLE
 *
 *   To not let mulle-sourcetree-to-c generate any header files:
 *
 *      mulle-sde environment set MULLE_SOURCETREE_TO_C_RUN DISABLE
 *
 */

// You can tweak the following #import with these commands.
// (Use B210821D-0D46-4542-B1AA-461B2F0E5ED2 instead of Foundation if there are duplicate entries)
//    remove #import: : `mulle-sde dependency mark Foundation no-header`
//    rename:              `mulle-sde dependency|library set Foundation include whatever.h`
//    reorder:             `mulle-sde dependency move Foundation <up|down>`
//    toggle #import:     `mulle-sde dependency mark Foundation [no-]import`
//    toggle public:       `mulle-sde dependency mark Foundation [no-]public`
//    toggle optional:     `mulle-sde dependency mark Foundation [no-]require`
//    remove for platform: `mulle-sde dependency mark Foundation no-platform-<uname>`
//        (use `mulle-sourcetree-to-c --unames` to list known values)
# if ! defined( __APPLE__)
# import <Foundation/Foundation.h>   // Foundation
#endif

// You can tweak the following #import with these commands.
// (Use 4F379C9A-8823-41A4-9071-C2917904AC61 instead of AppleFoundation if there are duplicate entries)
//    remove #import: : `mulle-sde dependency mark AppleFoundation no-header`
//    rename:              `mulle-sde dependency|library set AppleFoundation include whatever.h`
//    reorder:             `mulle-sde dependency move AppleFoundation <up|down>`
//    toggle #import:     `mulle-sde dependency mark AppleFoundation [no-]import`
//    toggle public:       `mulle-sde dependency mark AppleFoundation [no-]public`
//    toggle optional:     `mulle-sde dependency mark AppleFoundation [no-]require`
//    remove for platform: `mulle-sde dependency mark AppleFoundation no-platform-<uname>`
//        (use `mulle-sourcetree-to-c --unames` to list known values)
# if defined( __APPLE__)
# import <Foundation/Foundation.h>   // AppleFoundation
#endif

// You can tweak the following #include with these commands.
// (Use BA4D32C3-5C14-4A3B-9E15-A54699AD2634 instead of objc-compat if there are duplicate entries)
//    remove #include:: `mulle-sde dependency mark objc-compat no-header`
//    rename:              `mulle-sde dependency|library set objc-compat include whatever.h`
//    reorder:             `mulle-sde dependency move objc-compat <up|down>`
//    toggle #include:    `mulle-sde dependency mark objc-compat [no-]import`
//    toggle public:       `mulle-sde dependency mark objc-compat [no-]public`
//    toggle optional:     `mulle-sde dependency mark objc-compat [no-]require`
//    remove for platform: `mulle-sde dependency mark objc-compat no-platform-<uname>`
//        (use `mulle-sourcetree-to-c --unames` to list known values)
#include <objc-compat/objc-compat.h>   // objc-compat
